#!/usr/bin/env python3

import sys,math

def diviseurs(n):
    i = 2
    diviseurs = [1,n]
    while i <= math.sqrt(n):
        if n%i == 0:
            diviseurs.append(i)
            diviseurs.append(int(n/i))
        i += 1
    diviseurs.sort()
    return diviseurs

if __name__ == '__main__':
	print(diviseurs(int(sys.argv[1])))
